export const adminsInfo = [
  {
    id: 1,
    name: "John Carter",
    role: "Super Admin",
    phone: "+1 555-201-1123",
    email: "john.carter@adminpanel.com",
    status: "Active",
  },
  {
    id: 2,
    name: "Emily Watson",
    role: "Admin",
    phone: "+1 555-202-3344",
    email: "emily.watson@adminpanel.com",
    status: "Active",
  },
  {
    id: 3,
    name: "Michael Brown",
    role: "Moderator",
    phone: "+1 555-203-5566",
    email: "michael.brown@adminpanel.com",
    status: "Inactive",
  },
  {
    id: 4,
    name: "Sophia Johnson",
    role: "Support Admin",
    phone: "+1 555-204-7788",
    email: "sophia.johnson@adminpanel.com",
    status: "Active",
  },
  {
    id: 5,
    name: "Daniel Wilson",
    role: "Admin",
    phone: "+1 555-205-8899",
    email: "daniel.wilson@adminpanel.com",
    status: "Active",
  },
  {
    id: 6,
    name: "Olivia Martinez",
    role: "Moderator",
    phone: "+1 555-206-9900",
    email: "olivia.martinez@adminpanel.com",
    status: "Inactive",
  },
  {
    id: 7,
    name: "James Anderson",
    role: "Super Admin",
    phone: "+1 555-207-2233",
    email: "james.anderson@adminpanel.com",
    status: "Active",
  },
  {
    id: 8,
    name: "Ava Thompson",
    role: "Admin",
    phone: "+1 555-208-3344",
    email: "ava.thompson@adminpanel.com",
    status: "Inactive",
  },
  {
    id: 9,
    name: "William Harris",
    role: "Support Admin",
    phone: "+1 555-209-4455",
    email: "william.harris@adminpanel.com",
    status: "Active",
  },
  {
    id: 10,
    name: "Charlotte Lewis",
    role: "Moderator",
    phone: "+1 555-210-5566",
    email: "charlotte.lewis@adminpanel.com",
    status: "Active",
  }
];
