export const vendorsInfo = [
  {
    id: 1,
    name: "Alpha Traders",
    address: "12 Main Boulevard, Lahore",
    phone: "0300-1234567",
    email: "contact@alphatraders.com",
    status: "Active",
  },
  {
    id: 2,
    name: "Modern Supplies Co.",
    address: "45 Industrial Area, Faisalabad",
    phone: "0312-9876543",
    email: "info@modernsupplies.com",
    status: "Inactive",
  },
  {
    id: 3,
    name: "Premium Distribution",
    address: "89 Shahrah-e-Quaid, Karachi",
    phone: "0321-5566778",
    email: "sales@premiumdist.com",
    status: "Active",
  },
  {
    id: 4,
    name: "City Wholesale Mart",
    address: "22 Jail Road, Lahore",
    phone: "0305-3344556",
    email: "support@citymart.pk",
    status: "Active",
  },
  {
    id: 5,
    name: "Global Merchants",
    address: "14 Gulberg III, Lahore",
    phone: "0331-8899001",
    email: "admin@globalmerchants.com",
    status: "Inactive",
  },
  {
    id: 6,
    name: "Evergreen Suppliers",
    address: "77 Saddar Bazar, Rawalpindi",
    phone: "0308-4455667",
    email: "evergreen@supplyhub.com",
    status: "Active",
  },
  {
    id: 7,
    name: "Quick Source Industries",
    address: "5 SITE Area, Peshawar",
    phone: "0345-6677889",
    email: "qsindustries@gmail.com",
    status: "Active",
  },
  {
    id: 8,
    name: "BlueLine Enterprises",
    address: "103 I-8 Markaz, Islamabad",
    phone: "0301-9988776",
    email: "contact@blueline.pk",
    status: "Inactive",
  },
  {
    id: 9,
    name: "Metro Tech Supplies",
    address: "16 Model Town, Lahore",
    phone: "0322-4455779",
    email: "metro@techsupplies.com",
    status: "Active",
  },
  {
    id: 10,
    name: "Sunrise Distributors",
    address: "33 University Road, Quetta",
    phone: "0334-2233445",
    email: "sunrise@dist.com",
    status: "Active",
  },
];
